<h1><center>Numpy</center></h1>

## Questions 

21. How to print only 3 decimal places in python numpy array?
22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
23. How to limit the number of items printed in output of numpy array?
24. How to print the full numpy array without truncating
25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
26. How to extract a particular column from 1D array of tuples?
27. How to convert a 1d array of tuples to a 2d numpy array?
28. How to compute the mean, median, standard deviation of a numpy array?
29. How to normalize an array so the values range exactly between 0 and 1?
30. How to compute the softmax score?

In [1]:
import numpy as np
a=np.array([1.9875,3.6328,44.27382,10*np.exp(10),1.23,324,545,23,12,43,35])

In [2]:
a

array([1.98750000e+00, 3.63280000e+00, 4.42738200e+01, 2.20264658e+05,
       1.23000000e+00, 3.24000000e+02, 5.45000000e+02, 2.30000000e+01,
       1.20000000e+01, 4.30000000e+01, 3.50000000e+01])

In [3]:
#1
np.set_printoptions(3)

In [4]:
a

array([1.988e+00, 3.633e+00, 4.427e+01, 2.203e+05, 1.230e+00, 3.240e+02,
       5.450e+02, 2.300e+01, 1.200e+01, 4.300e+01, 3.500e+01])

In [5]:
#2
np.set_printoptions(suppress=True)

In [6]:
a

array([     1.988,      3.633,     44.274, 220264.658,      1.23 ,
          324.   ,    545.   ,     23.   ,     12.   ,     43.   ,
           35.   ])

In [7]:
#3
np.set_printoptions(threshold=2)

In [8]:
a

array([ 1.988,  3.633, 44.274, ..., 12.   , 43.   , 35.   ])

In [9]:
#4
np.set_printoptions(threshold=np.inf)

In [10]:
a

array([     1.988,      3.633,     44.274, 220264.658,      1.23 ,
          324.   ,    545.   ,     23.   ,     12.   ,     43.   ,
           35.   ])

In [11]:
#5
df=np.loadtxt(fname = {filepath}) 

NameError: name 'filepath' is not defined

In [12]:
#6
b=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [13]:
#extracting first column
b[:,0]

array([1, 4, 7])

In [14]:
#7
c=[(1,2,3),(4,5,6)]
np.array(c)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#8
mean_a=np.mean(a)
median_a=np.median(a)
std_a=np.std(a)

In [16]:
mean_a

20117.98018800611

In [17]:
median_a

35.0

In [18]:
std_a

63292.15294785072

In [19]:
#9
norm_a=(a-np.min(a))/(np.max(a)-np.min(a))

In [20]:
norm_a

array([0.   , 0.   , 0.   , 1.   , 0.   , 0.001, 0.002, 0.   , 0.   ,
       0.   , 0.   ])

In [21]:
#10
soft_a=np.exp(a) / np.sum(np.exp(a), axis=0)

/home/shashank/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/home/shashank/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


In [22]:
soft_a

array([ 0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.])